### ISSUE TITLE
undefined method Doku_Handler::getStatus()

### ISSUE THREAD

**Issue by Brazier85** [Medieninformatik-Regensburg/dokuwiki-plugin-markdowku#1]
Hello,
after installing I got the following error:

````

Fatal error: Uncaught Error: Call to undefined method Doku_Handler::getStatus() in /var/www/vhosts/xx/httpdocs/lib/plugins/markdowku/syntax/headeratx.php:39 Stack trace: #0 /var/www/vhosts/xx/httpdocs/inc/parser/handler.php(240): syntax_plugin_markdowku_headeratx->handle('\n### Welcome to...', 5, 0, Object(Doku_Handler)) #1 /var/www/vhosts/xx/httpdocs/inc/Parsing/Lexer/Lexer.php(278): Doku_Handler->plugin('\n### Welcome to...', 5, 0, 'markdowku_heade...') #2 /var/www/vhosts/xx/httpdocs/inc/Parsing/Lexer/Lexer.php(205): dokuwiki\Parsing\Lexer\Lexer->invokeHandler('\n### Welcome to...', 5, 0) #3 /var/www/vhosts/xx/httpdocs/inc/Parsing/Lexer/Lexer.php(155): dokuwiki\Parsing\Lexer\Lexer->dispatchTokens('', '\n### Welcome to...', '_plugin_markdow...', 0, 0) #4 /var/www/vhosts/xx/httpdocs/inc/Parsing/Parser.php(109): dokuwiki\Parsing\Lexer\Lexer->parse('\n\nFor a long ti...') #5 /var/www/vhosts/xx/httpdocs/inc/parserutils.php(216): dokuwiki\Parsing\Parser->pa in /var/www/vhosts/xx/httpdocs/lib/plugins/markdowku/syntax/headeratx.php on line 39
````

**Comment by RaphaelWimmer** [comment]
This issue should have been fixed since Hogfather. See [plugin page](https://www.dokuwiki.org/plugin:markdowku?rev=1591480488) for background. Please reopen if necessary.
